version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    command: ["serve"]
    entrypoint: ["/bin/sh", "-c", "ollama pull mistral && ollama serve"]


  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    ports:
      - "8000:8000"

volumes:
  ollama_data:
